{{- if .Values.endpoint.auth.enabled }}
{{- range $serviceAccount := .Values.endpoint.auth.serviceAccounts }}
{{- if list nil true | has $serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
  namespace: {{ $serviceAccount.namespace | default $.Release.Namespace }}
  labels:
    {{- include "guardrails-hf-detector-kserve.labels" $ | nindent 4 }}
{{ if list nil true | has $serviceAccount.createLegacyToken }}
secrets:
  - name: {{ $serviceAccount.name }}
{{- end }}
automountServiceAccountToken: true
{{ if list nil true | has $serviceAccount.createLegacyToken }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ $serviceAccount.name }}
  annotations:
    kubernetes.io/service-account.name: {{ $serviceAccount.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
